apiVersion: v1
kind: ConfigMap
metadata:
  name: polis-server
data:
  #General Settings
  ADMIN_UIDS: "[]"
  GIT_HASH: ""
  SERVER_ENV_FILE: ".env"

  # Database
  READ_ONLY_DATABASE_URL: ""
  POSTGRES_DOCKER: "true"
  DATABASE_FOR_READS_NAME: DATABASE_URL

  # Set to `false` for production
  DEV_MODE: "true"

  # Set the domain name; make sure this matches what"s running on math node
  DOMAIN_OVERRIDE: polis.local
  API_DEV_HOSTNAME: polis.local
  API_PROD_HOSTNAME: polis.local

  # Options: prod, preprod, dev
  MATH_ENV: dev
  PORT: "5000"

  # Set to `true` and insert google creds if desired
  SHOULD_USE_TRANSLATION_API: "false"
  # GOOGLE_CREDENTIALS_BASE64: ...
  # GOOGLE_CREDS_STRINGIFIED: ...

  # These need to be configured to point to the local file server
  STATIC_FILES_HOST: polis-file-server
  STATIC_FILES_ADMINDASH_PORT: "80"
  STATIC_FILES_PORT: "80"

  AWS_REGION: us-east-1

  # Options: maildev, aws-ses, mailgun
  EMAIL_TRANSPORT_TYPES: maildev
  POLIS_FROM_ADDRESS: "Example <team@example.com>"

  # These pieces of functionality will likely be removed in the near future
  DISABLE_INTERCOM: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: polis-server
spec:
  selector:
    matchLabels:
      app: polis-server
  template:
    metadata:
      labels:
        app: polis-server
    spec:
      containers:
        - image: docker.io/compdem/polis-server:dev
          name: polis-server
          env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: polis-secret
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: polis-secret
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: polis-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: polis-secret
                key: POSTGRES_HOST
          - name: DATABASE_URL
            value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST)/$(POSTGRES_DB)
          - name: STRIPE_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: polis-secret
                key: STRIPE_SECRET_KEY
          - name: ENCRYPTION_PASSWORD_00001
            valueFrom:
              secretKeyRef:
                name: polis-secret
                key: ENCRYPTION_PASSWORD_00001
          envFrom:
          - configMapRef:
              name: polis-server
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
---
apiVersion: v1
kind: Service
metadata:
  name: polis-server
spec:
  ports:
    - name: http
      port: 80
      targetPort: 5000
  selector:
    app: polis-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: polis-server
spec:
  rules:
    - host: polis.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: polis-server
                port:
                  number: 80


